[tox]
envlist =
    black-check
    {Plone60}-{py310,py311}
min_version = 4

[gh-actions]
python =
    3.10: py310
    3.11: py311

[gh-actions:env]
PLONE-VERSION =
    Plone60: Plone60

[testenv:{Plone60}-{py310,py311}]
skip_install = true
deps =
    zc.buildout==4.1.4
    setuptools==75.8.2
allowlist_externals =
    buildout
    bin/test
setenv =
    PLONE_CFG = test_plone60.cfg
commands =
    buildout -c {env:PLONE_CFG} bootstrap
    buildout -c {env:PLONE_CFG}
    bin/test

[testenv:black-check]
skip_install = true
deps = black==26.5.1
commands = black --check src
