[tox]
envlist =
    black-check
    {Plone52,Plone60}-{py38,py39,py310}
min_version = 4

[gh-actions]
python =
    3.8: py38
    3.9: py39
    3.10: py310

[gh-actions:env]
PLONE-VERSION =
    Plone52: Plone52
    Plone60: Plone60

[testenv:{Plone52,Plone60}-{py38,py39,py310}]
skip_install = true
deps =
    zc.buildout
    setuptools
allowlist_externals =
    buildout
    bin/test
setenv =
    Plone52: PLONE_CFG = test_plone52.cfg
    Plone60: PLONE_CFG = test_plone60.cfg
commands =
    buildout -c {env:PLONE_CFG} bootstrap
    buildout -c {env:PLONE_CFG}
    bin/test

[testenv:black-check]
skip_install = true
deps = black
commands = black --check src
